#!/bin/bash
# Deploy the spinning-wheel real-time backend + static frontend.
# Intended to run in AWS CloudShell (native creds, SAM + AWS CLI preinstalled).
set -euo pipefail

STACK="${STACK:-spinning-wheel}"
REGION="${AWS_REGION:-us-east-1}"
STAMP="$(date +%s)"
BUCKET="spinning-wheel-site-${STAMP}"

# Optional CORS origin override. If you already know the CloudFront (or custom)
# origin, set ALLOWED_ORIGIN=https://... and it is passed to the initial deploy
# so the REST API is locked to that origin from the start. On a fresh first run
# the origin is not known yet (the CloudFront distribution is created later in
# this script), so leave it empty: the initial deploy uses the template default
# ("*") and step 6 below re-deploys to pin the real CloudFront origin.
ALLOWED_ORIGIN="${ALLOWED_ORIGIN:-}"

echo ">> Stack: $STACK | Region: $REGION | Site bucket: $BUCKET"

# ---- 1. Build & deploy the SAM backend ----
sam build
DEPLOY_ARGS=(
  --stack-name "$STACK"
  --region "$REGION"
  --resolve-s3
  --capabilities CAPABILITY_IAM
  --no-confirm-changeset
  --no-fail-on-empty-changeset
)
if [ -n "$ALLOWED_ORIGIN" ]; then
  echo ">> Pinning CORS AllowedOrigin=$ALLOWED_ORIGIN on initial deploy"
  DEPLOY_ARGS+=(--parameter-overrides "AllowedOrigin=$ALLOWED_ORIGIN")
fi
sam deploy "${DEPLOY_ARGS[@]}"

# ---- 2. Read stack outputs ----
REST_URL=$(aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='RestApiUrl'].OutputValue" --output text)
WS_URL=$(aws cloudformation describe-stacks --stack-name "$STACK" --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='WebSocketUrl'].OutputValue" --output text)

echo ">> RestApiUrl:  $REST_URL"
echo ">> WebSocketUrl: $WS_URL"

# ---- 3. Inject the URLs into config.js ----
cat > config.js <<EOF
// Generated by deploy.sh — do not edit by hand.
window.APP_CONFIG = {
  REST_API_URL: "${REST_URL}",
  WEBSOCKET_URL: "${WS_URL}",
};
EOF

# ---- 4. Host the static frontend on S3 + CloudFront ----
if [ "$REGION" = "us-east-1" ]; then
  aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" >/dev/null
else
  aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
    --create-bucket-configuration LocationConstraint="$REGION" >/dev/null
fi

upload() { aws s3 cp "$1" "s3://$BUCKET/$1" --content-type "$2"; }
upload index.html    "text/html"
upload register.html "text/html"
upload wheel-logic.js "text/javascript"
upload config.js      "text/javascript"
aws s3 cp vendor/qrcode.min.js "s3://$BUCKET/vendor/qrcode.min.js" --content-type "text/javascript"

OAC_ID=$(aws cloudfront create-origin-access-control \
  --origin-access-control-config \
  "Name=oac-${STAMP},SigningProtocol=sigv4,SigningBehavior=always,OriginAccessControlOriginType=s3" \
  --query 'OriginAccessControl.Id' --output text)

cat > /tmp/dist.json <<EOF
{
  "CallerReference": "${STAMP}",
  "Comment": "spinning-wheel-site",
  "Enabled": true,
  "DefaultRootObject": "index.html",
  "Origins": { "Quantity": 1, "Items": [{
    "Id": "s3-${BUCKET}",
    "DomainName": "${BUCKET}.s3.${REGION}.amazonaws.com",
    "OriginAccessControlId": "${OAC_ID}",
    "S3OriginConfig": { "OriginAccessIdentity": "" }
  }]},
  "DefaultCacheBehavior": {
    "TargetOriginId": "s3-${BUCKET}",
    "ViewerProtocolPolicy": "redirect-to-https",
    "CachePolicyId": "658327ea-f89d-4fab-a63d-7e88639e58f6",
    "Compress": true
  }
}
EOF

DIST_OUT=$(aws cloudfront create-distribution --distribution-config file:///tmp/dist.json)
DIST_ID=$(echo "$DIST_OUT"  | python3 -c "import sys,json;print(json.load(sys.stdin)['Distribution']['Id'])")
DIST_DOM=$(echo "$DIST_OUT" | python3 -c "import sys,json;print(json.load(sys.stdin)['Distribution']['DomainName'])")

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
cat > /tmp/policy.json <<EOF
{ "Version": "2012-10-17", "Statement": [{
  "Sid": "AllowCloudFront", "Effect": "Allow",
  "Principal": { "Service": "cloudfront.amazonaws.com" },
  "Action": "s3:GetObject", "Resource": "arn:aws:s3:::${BUCKET}/*",
  "Condition": { "StringEquals": {
    "AWS:SourceArn": "arn:aws:cloudfront::${ACCOUNT_ID}:distribution/${DIST_ID}" } }
}]}
EOF
aws s3api put-bucket-policy --bucket "$BUCKET" --policy file:///tmp/policy.json

# ---- 5. Pin CORS to the CloudFront origin ----
# The template default AllowedOrigin is "*" (dev convenience). Now that the
# distribution exists and $DIST_DOM is known, run a lightweight re-deploy to
# lock the REST API CORS to the real CloudFront origin. Skipped if the caller
# already pinned ALLOWED_ORIGIN on the initial deploy above.
if [ -z "$ALLOWED_ORIGIN" ]; then
  echo ">> Pinning CORS AllowedOrigin=https://${DIST_DOM} (re-deploy)"
  sam deploy \
    --stack-name "$STACK" \
    --region "$REGION" \
    --resolve-s3 \
    --capabilities CAPABILITY_IAM \
    --no-confirm-changeset \
    --no-fail-on-empty-changeset \
    --parameter-overrides "AllowedOrigin=https://${DIST_DOM}"
fi

# ---- 6. Invalidate the CloudFront cache ----
# After re-uploading the static site, CloudFront may still serve stale objects
# from its edge caches. Invalidate everything so the new files are served.
# Prefer an existing distribution id from the environment (CF_DIST_ID / SW_DIST)
# when re-deploying against an already-provisioned distribution; otherwise fall
# back to the id of the distribution just created above.
INVALIDATE_DIST="${CF_DIST_ID:-${SW_DIST:-$DIST_ID}}"
if [ -n "$INVALIDATE_DIST" ]; then
  echo ">> Requesting CloudFront invalidation for $INVALIDATE_DIST (/*)"
  # Gated on a non-empty id above; `|| true` keeps a benign invalidation
  # failure from aborting the whole script under `set -euo pipefail`.
  aws cloudfront create-invalidation --distribution-id "$INVALIDATE_DIST" --paths '/*' || true
fi

echo ""
echo "==================================================================="
echo " Deployed. CloudFront provisioning (~5-10 min the first time)."
echo ""
echo "   Presenter wheel:  https://${DIST_DOM}/index.html"
echo ""
echo "   Stack:         $STACK"
echo "   Site bucket:   $BUCKET"
echo "   Distribution:  $DIST_ID"
echo "==================================================================="
echo "export SW_STACK=$STACK SW_BUCKET=$BUCKET SW_DIST=$DIST_ID"
